LOCAL_PATH:= $(call my-dir)

# build device static library
include $(CLEAR_VARS)

LOCAL_SRC_FILES:= \
	reboot.c

LOCAL_MODULE:= libreboot

ifneq ($(TARGET_REBOOT_PRE_COMMAND),)
        LOCAL_CFLAGS += -DREBOOT_PRE_COMMAND='$(TARGET_REBOOT_PRE_COMMAND)'
endif
ifneq ($(TARGET_REBOOT_PRE_COMMAND_CLEAR_REASON),)
        LOCAL_CFLAGS += -DREBOOT_PRE_COMMAND_CLEAR_REASON
endif


ifneq ($(TARGET_RECOVERY_PRE_COMMAND),)
	LOCAL_CFLAGS += -DRECOVERY_PRE_COMMAND='$(TARGET_RECOVERY_PRE_COMMAND)'
endif
ifneq ($(TARGET_RECOVERY_PRE_COMMAND_CLEAR_REASON),)
	LOCAL_CFLAGS += -DRECOVERY_PRE_COMMAND_CLEAR_REASON
endif

ifneq ($(TARGET_REBOOT_REASON_DEFAULT),)
        LOCAL_CFLAGS += -DREBOOT_REASON_DEFAULT='$(TARGET_REBOOT_REASON_DEFAULT)'
endif

include $(BUILD_STATIC_LIBRARY)


# build device static library
include $(CLEAR_VARS)

LOCAL_SRC_FILES:= \
	reboot.c

LOCAL_MODULE:= librebootrecovery

ifneq ($(TARGET_RECOVERY_PRE_COMMAND),)
	LOCAL_CFLAGS += -DRECOVERY_PRE_COMMAND='$(TARGET_RECOVERY_PRE_COMMAND)'
endif

ifneq ($(TARGET_RECOVERY_PRE_COMMAND_CLEAR_REASON),)
	LOCAL_CFLAGS += -DRECOVERY_PRE_COMMAND_CLEAR_REASON
endif

LOCAL_CFLAGS += -DRECOVERY_SHELL
LOCAL_STATIC_LIBRARIES += libcrecovery

include $(BUILD_STATIC_LIBRARY)
